import { useState } from 'react';
import { Modal } from 'flowbite-react';
import { toast } from 'react-toastify';

type Row = { line: number; data?: Record<string, string>; school_id?: string; email?: string; valid?: boolean; status?: string; activation_link?: string | null; errors?: string[]; error?: string | null };
export default function MemberImportModal({ open, onClose }: { open: boolean; onClose: () => void }) {
  const [file, setFile] = useState<File | null>(null); const [hash, setHash] = useState(''); const [rows, setRows] = useState<Row[]>([]); const [busy, setBusy] = useState(false); const [committed, setCommitted] = useState(false);
  const send = async (mode: 'preview' | 'commit') => { if (!file) return; setBusy(true); try { const form = new FormData(); form.append('file', file); form.append('mode', mode); if (hash) form.append('content_hash', hash); const response = await fetch('/my-app-server/import_members.php', { method: 'POST', credentials: 'include', body: form }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Import failed'); if (mode === 'preview') { setHash(data.content_hash); setRows(data.rows); } else { setRows(data.rows || []); setCommitted(true); } } catch (error) { toast.error(error instanceof Error ? error.message : 'Import failed'); } finally { setBusy(false); } };
  const download = () => { const escape = (value: unknown) => `"${String(value ?? '').replace(/"/g, '""')}"`; const csv = ['line,school_id,email,status,activation_link,error', ...rows.map(row => [row.line, row.school_id, row.email, row.status, row.activation_link, row.error].map(escape).join(','))].join('\r\n'); const anchor = document.createElement('a'); anchor.href = URL.createObjectURL(new Blob([csv], { type: 'text/csv' })); anchor.download = 'imscca-member-invitations.csv'; anchor.click(); URL.revokeObjectURL(anchor.href); };
  return (
    <Modal dismissible show={open} onClose={onClose} size="5xl">
      <Modal.Header>Import member invitations</Modal.Header>
      <Modal.Body><div className="space-y-4"><p className="text-sm text-gray-600 dark:text-gray-300">UTF-8 CSV headers: school_id, email, first_name, middle_name, last_name, course, year, section</p><label className="block text-sm font-medium">CSV file<input type="file" accept=".csv,text/csv" onChange={event => { setFile(event.target.files?.[0] || null); setRows([]); setHash(''); setCommitted(false); }} className="mt-1 block w-full text-sm" /></label><div className="max-h-96 overflow-auto rounded border" tabIndex={0} aria-label="Import preview"><table className="w-full min-w-[700px] text-left text-sm"><thead><tr>{['Line', 'School ID', 'Email', 'Status', 'Error'].map(heading => <th key={heading} className="p-2">{heading}</th>)}</tr></thead><tbody>{rows.map(row => <tr key={row.line} className="border-t"><td className="p-2">{row.line}</td><td className="p-2">{row.school_id || row.data?.school_id}</td><td className="p-2">{row.email || row.data?.email}</td><td className="p-2">{row.status || (row.valid ? 'valid' : 'invalid')}</td><td className="p-2 text-red-600">{row.error || row.errors?.join('; ')}</td></tr>)}</tbody></table></div></div></Modal.Body>
      <Modal.Footer><button className="rounded bg-primary-600 px-4 py-2 text-white disabled:opacity-50" disabled={!file || busy || committed} onClick={() => void send(hash ? 'commit' : 'preview')}>{busy ? 'Working...' : hash ? 'Commit invitations' : 'Preview'}</button>{committed && <button className="rounded border px-4 py-2" onClick={download}>Download results CSV</button>}<button className="rounded border px-4 py-2" onClick={onClose}>Close</button></Modal.Footer>
    </Modal>
  );
}
