import { useCallback, useEffect, useState } from 'react';
import Sidebar from './components/Sidebar';
import Breadcrumb from './components/Breadcrumb';

interface AuditItem { audit_id:number; action:string; entity_type:string; entity_id:number|null; actor_name:string|null; subject_name:string|null; created_at:string; metadata:Record<string,unknown>|null }

export default function History() {
  const [items,setItems]=useState<AuditItem[]>([]); const [page,setPage]=useState(1); const [total,setTotal]=useState(0);
  const [action,setAction]=useState(''); const [entity,setEntity]=useState(''); const limit=25;
  const [actorId,setActorId]=useState(''); const [from,setFrom]=useState(''); const [to,setTo]=useState('');
  const load=useCallback(async()=>{const p=new URLSearchParams({page:String(page),limit:String(limit)});if(action)p.set('action',action);if(entity)p.set('entity_type',entity);if(actorId)p.set('actor_id',actorId);if(from)p.set('from',from);if(to)p.set('to',to);
    const r=await fetch(`/my-app-server/get_history.php?${p}`,{credentials:'include'}); const data=await r.json(); if(r.ok){setItems(data.items);setTotal(data.total)}},[page,action,entity,actorId,from,to]);
  useEffect(()=>{void load()},[load]);
  return <div className="min-h-screen bg-gray-50 dark:bg-gray-900"><Sidebar/><main className="min-w-0 p-4 pt-24 sm:ml-64 sm:p-6 sm:pt-24">
    <Breadcrumb items={[{label:'Home',to:'/dashboard'},{label:'History'}]}/>
    <div className="mb-5 flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div><h1 className="text-2xl font-semibold text-gray-900 dark:text-white">History</h1><p className="text-sm text-gray-600 dark:text-gray-400">Recorded club activity and account changes</p></div>
      <div className="grid grid-cols-1 gap-2 sm:grid-cols-2 lg:grid-cols-5"><label className="text-sm text-gray-700 dark:text-gray-300">Action<input value={action} onChange={e=>{setAction(e.target.value);setPage(1)}} className="mt-1 w-full rounded border p-2 dark:bg-gray-800" placeholder="Action"/></label><label className="text-sm text-gray-700 dark:text-gray-300">Entity<input value={entity} onChange={e=>{setEntity(e.target.value);setPage(1)}} className="mt-1 w-full rounded border p-2 dark:bg-gray-800" placeholder="Entity"/></label><label className="text-sm text-gray-700 dark:text-gray-300">Actor ID<input type="number" value={actorId} onChange={e=>{setActorId(e.target.value);setPage(1)}} className="mt-1 w-full rounded border p-2 dark:bg-gray-800"/></label><label className="text-sm text-gray-700 dark:text-gray-300">From<input type="date" value={from} onChange={e=>{setFrom(e.target.value);setPage(1)}} className="mt-1 w-full rounded border p-2 dark:bg-gray-800"/></label><label className="text-sm text-gray-700 dark:text-gray-300">To<input type="date" value={to} onChange={e=>{setTo(e.target.value);setPage(1)}} className="mt-1 w-full rounded border p-2 dark:bg-gray-800"/></label></div></div>
    <div className="overflow-hidden rounded border border-gray-200 bg-white dark:border-gray-700 dark:bg-gray-800"><div className="hidden overflow-x-auto md:block"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-gray-100 dark:bg-gray-700"><tr>{['When','Action','Entity','Actor','Affected user','Details'].map(h=><th key={h} className="px-4 py-3">{h}</th>)}</tr></thead><tbody>{items.map(i=><tr key={i.audit_id} className="border-t dark:border-gray-700"><td className="whitespace-nowrap px-4 py-3">{new Date(i.created_at).toLocaleString()}</td><td className="px-4 py-3 font-medium">{i.action.replace(/_/g,' ')}</td><td className="px-4 py-3">{i.entity_type}{i.entity_id?` #${i.entity_id}`:''}</td><td className="px-4 py-3">{i.actor_name||'System'}</td><td className="px-4 py-3">{i.subject_name||'-'}</td><td className="max-w-xs truncate px-4 py-3" title={i.metadata?JSON.stringify(i.metadata):''}>{i.metadata?JSON.stringify(i.metadata):'-'}</td></tr>)}</tbody></table></div>
      <div className="divide-y dark:divide-gray-700 md:hidden">{items.map(i=><article key={i.audit_id} className="space-y-1 p-4"><div className="flex justify-between gap-3"><strong>{i.action.replace(/_/g,' ')}</strong><time className="text-xs text-gray-500">{new Date(i.created_at).toLocaleString()}</time></div><p className="text-sm">{i.entity_type}{i.entity_id?` #${i.entity_id}`:''}</p><p className="text-sm text-gray-600 dark:text-gray-400">By {i.actor_name||'System'}{i.subject_name?` for ${i.subject_name}`:''}</p></article>)}</div>
      {!items.length&&<p className="p-8 text-center text-gray-500">No history entries found.</p>}</div>
    <div className="mt-4 flex items-center justify-between"><span className="text-sm text-gray-600 dark:text-gray-400">{total} entries</span><div className="flex gap-2"><button disabled={page===1} onClick={()=>setPage(p=>p-1)} className="rounded border px-3 py-2 disabled:opacity-40">Previous</button><button disabled={page*limit>=total} onClick={()=>setPage(p=>p+1)} className="rounded border px-3 py-2 disabled:opacity-40">Next</button></div></div>
  </main></div>
}
